// Generated by .dbot Compiler
const { Client, GatewayIntentBits, REST, Routes, ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType, PermissionFlagsBits, MessageFlags } = require('discord.js');

const client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMessages,
        GatewayIntentBits.MessageContent,
        GatewayIntentBits.GuildMembers
    ]
});

// Runtime Helper for Answers and Message Sending (abstracting deferred/replied interaction state)
async function sendReply(interaction, content, ephemeral = false, components = []) {
    const payload = { content: content };
    if (components && components.length > 0) {
        payload.components = components;
    }
    if (ephemeral) {
        payload.flags = MessageFlags.Ephemeral;
    }
    
    try {
        if (interaction.replied || interaction.deferred) {
            return await interaction.followUp(payload);
        } else {
            return await interaction.reply(payload);
        }
    } catch (error) {
        console.error("Error sending response:", error);
    }
}

// Global Variables
let total_commands = 0;
let secret_code = 42;

// Custom Functions
async function increment_counter(interaction) {
    total_commands = (total_commands + 1);
    console.log("Global command count incremented to: " + total_commands)
}

// Ready Listener (slash command registration)
client.once('clientReady', async () => {
    console.log(`Logged in as ${client.user.tag}!`);
    
    const commands = [
        { name: 'ping', description: 'Command /ping' },
        { name: 'admin-panel', description: 'Command /admin-panel' }
    ];
    
    const rest = new REST({ version: '10' }).setToken(process.env.DISCORD_TOKEN || 'YOUR_BOT_TOKEN');
    try {
        console.log('Started refreshing application (/) commands.');
        await rest.put(
            Routes.applicationCommands(client.user.id),
            { body: commands },
        );
        console.log('Successfully reloaded application (/) commands.');
    } catch (error) {
        console.error('Error reloading application (/) commands:', error);
    }
});

// Interaction Listener
client.on('interactionCreate', async interaction => {
    if (interaction.isChatInputCommand()) {
        const { commandName } = interaction;
        if (commandName === 'ping') {
        await increment_counter(interaction);
        await sendReply(interaction, "Pong! Active connection established.", true, []);
    }
        if (commandName === 'admin-panel') {
        await increment_counter(interaction);
        if (!interaction.member.permissions.has(PermissionFlagsBits.Administrator)) {
    await sendReply(interaction, "Access Denied: Administrator role required!", true, []);
}
        if (interaction.member.permissions.has(PermissionFlagsBits.Administrator)) {
    await sendReply(interaction, "Welcome to the Admin control room. Choose an action:", false, [
        new ActionRowBuilder().addComponents(
            new ButtonBuilder()
                .setCustomId("btn_create_channel")
                .setLabel("Create Temp Channel")
                .setStyle(ButtonStyle.Success),
            new ButtonBuilder()
                .setCustomId("btn_broadcast")
                .setLabel("Run Broadcast")
                .setStyle(ButtonStyle.Success)
        )
    ]);
}
    }
    } else if (interaction.isButton()) {
        const { customId } = interaction;
        if (customId === 'btn_create_channel') {
        await sendReply(interaction, "Creating private channel...", true, []);
        let name_base = "admin-secret";
        const channel = await interaction.guild.channels.create({
        name: name_base,
        type: ChannelType.GuildText,
        permissionOverwrites: [
            {
                id: interaction.guild.roles.everyone.id,
                deny: [PermissionFlagsBits.ViewChannel],
            },
            {
                id: interaction.user.id,
                allow: [PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages],
            }
        ]
    });
        await sendReply(interaction, "Private channel created successfully!", false, []);
    }
        if (customId === 'btn_broadcast') {
        await sendReply(interaction, "Starting loop alert...", true, []);
        for (let i_1 = 0; i_1 < 3; i_1++) {
    await sendReply(interaction, "Alert! System check in progress.", false, []);
}
        console.log("Completed broadcast loop.")
    }
    }
});

client.login(process.env.DISCORD_TOKEN || 'YOUR_BOT_TOKEN');
